services:
  postgres:
    image: postgres:16
    container_name: postgres_dumbledoor
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "32432:5432"
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_dumbledoor
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ client port
      - "15672:15672" # RabbitMQ management web UI
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
