services:
  postgres:
    image: postgres:16
    container_name: postgres_dumbledoor
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "32432:5432"
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_dumbledoor
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ client port
      - "15672:15672" # RabbitMQ management web UI
    networks:
      - backend

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt_dumbledoor
    volumes:
    //- '/mosquitto/config/mosquitto.conf:/mosquitto-no-auth.conf'
    ports:
      - "1883:1883"  # MQTT Broker port
      - "9001:9001"  # MQTT WebSocket port
    networks:
      - backend  # Corrected to be an array
      
volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
